#!/bin/bash
SOURCE_ACCOUNT="947332944497"
PROFILE_AXA="default"
SOURCE_ACCOUNT_REGION="eu-central-1"
DESTINATION_ACCOUNT_REGION="eu-central-1"
DESTINATION_ACCOUNT="650257924275"
SOURCE_ACCOUNT_BASE_PATH="$SOURCE_ACCOUNT.dkr.ecr.$SOURCE_ACCOUNT_REGION.amazonaws.com"
DESTINATION_ACCOUNT_BASE_PATH="$DESTINATION_ACCOUNT.dkr.ecr.$DESTINATION_ACCOUNT_REGION.amazonaws.com"
aws ecr get-login-password --region $SOURCE_ACCOUNT_REGION --profile $PROFILE_AXA | docker login --username AWS --password-stdin $SOURCE_ACCOUNT_BASE_PATH
aws ecr get-login-password --region $DESTINATION_ACCOUNT_REGION --profile $PROFILE_AXA | docker login --username AWS --password-stdin $DESTINATION_ACCOUNT_BASE_PATH

REPO=("sherlock-ml-forgery-detector" )
DESTINATION_REPO_NAME=$(echo $REPO | sed -e "s/sherlock/shck/g")
echo "destination repo_name is $DESTINATION_REPO_NAME"
TAG_LIST=("v2.1.7" "v2.1.8" "v2.2.3")

for tag in ${TAG_LIST[@]}; do
  CURRENT_IMAGE_TAG=$tag
  CURRENT_IMAGE_URI=$SOURCE_ACCOUNT_BASE_PATH/$REPO:$CURRENT_IMAGE_TAG
  DESTINATION_IMAGE_URI=$DESTINATION_ACCOUNT_BASE_PATH/$DESTINATION_REPO_NAME:$CURRENT_IMAGE_TAG
  echo "pull from $CURRENT_IMAGE_URI"
  docker pull $CURRENT_IMAGE_URI
  docker tag  $CURRENT_IMAGE_URI $DESTINATION_IMAGE_URI
  echo "push to $DESTINATION_IMAGE_URI"
  docker push $DESTINATION_IMAGE_URI
done

REPO=("tonistiigi/binfmt" )
DESTINATION_REPO_NAME=$(echo $REPO | sed -e "s/sherlock/shck/g")
echo "destination repo_name is $DESTINATION_REPO_NAME"
TAG_LIST=("latest")

for tag in ${TAG_LIST[@]}; do
  CURRENT_IMAGE_TAG=$tag
  CURRENT_IMAGE_URI=$SOURCE_ACCOUNT_BASE_PATH/$REPO:$CURRENT_IMAGE_TAG
  DESTINATION_IMAGE_URI=$DESTINATION_ACCOUNT_BASE_PATH/$DESTINATION_REPO_NAME:$CURRENT_IMAGE_TAG
  echo "pull from $CURRENT_IMAGE_URI"
  docker pull $CURRENT_IMAGE_URI
  docker tag  $CURRENT_IMAGE_URI $DESTINATION_IMAGE_URI
  echo "push to $DESTINATION_IMAGE_URI"
  docker push $DESTINATION_IMAGE_URI
done

REPO=("ecr-public/docker/library/node" )
DESTINATION_REPO_NAME=$(echo $REPO | sed -e "s/sherlock/shck/g")
echo "destination repo_name is $DESTINATION_REPO_NAME"
TAG_LIST=("16.15.0-alpine3.15" "16.15.1-alpine3.15" "16.15-alpine3.15")

for tag in ${TAG_LIST[@]}; do
  CURRENT_IMAGE_TAG=$tag
  CURRENT_IMAGE_URI=$SOURCE_ACCOUNT_BASE_PATH/$REPO:$CURRENT_IMAGE_TAG
  DESTINATION_IMAGE_URI=$DESTINATION_ACCOUNT_BASE_PATH/$DESTINATION_REPO_NAME:$CURRENT_IMAGE_TAG
  echo "pull from $CURRENT_IMAGE_URI"
  docker pull $CURRENT_IMAGE_URI
  docker tag  $CURRENT_IMAGE_URI $DESTINATION_IMAGE_URI
  echo "push to $DESTINATION_IMAGE_URI"
  docker push $DESTINATION_IMAGE_URI
done

REPO=("ecr-public/docker/library/python" )
DESTINATION_REPO_NAME=$(echo $REPO | sed -e "s/sherlock/shck/g")
echo "destination repo_name is $DESTINATION_REPO_NAME"
TAG_LIST=("3.8")

for tag in ${TAG_LIST[@]}; do
  CURRENT_IMAGE_TAG=$tag
  CURRENT_IMAGE_URI=$SOURCE_ACCOUNT_BASE_PATH/$REPO:$CURRENT_IMAGE_TAG
  DESTINATION_IMAGE_URI=$DESTINATION_ACCOUNT_BASE_PATH/$DESTINATION_REPO_NAME:$CURRENT_IMAGE_TAG
  echo "pull from $CURRENT_IMAGE_URI"
  docker pull $CURRENT_IMAGE_URI
  docker tag  $CURRENT_IMAGE_URI $DESTINATION_IMAGE_URI
  echo "push to $DESTINATION_IMAGE_URI"
  docker push $DESTINATION_IMAGE_URI
done
